package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Friday, February 8, 2019 10:54:42 AM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
